name: Deploy Blog

on:
  push:
    branches:
      - main  # 监听 main 分支的变动

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 拉取代码
        uses: actions/checkout@v4
        with:
          submodules: true  # ✅ 必须开启，否则 Diary 主题为空
          fetch-depth: 0

      - name: 2. 安装 Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true   # ✅ 必须开启 Extended 版本

      - name: 3. 编译博客
        run: hugo --minify

      - name: 4. 部署到阿里云
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          source: "public/"
          target: "/var/www/html/tekapo-blog/"
          strip_components: 1 # ✅ 移除 public 这一层，直接放内容